/* tslint:disable */
/* eslint-disable */
/**
 * tollgator-core
 * Full api description goes here
 *
 * The version of the OpenAPI document: 1.0
 * Contact: joshuanwafor01@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    publisherId?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    courseCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    _abstract?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    status?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Course
     */
    categories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    photo?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    coverPhoto?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    ?: string;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'publisherId': !exists(json, 'publisher_id') ? undefined : json['publisher_id'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'courseCode': !exists(json, 'course_code') ? undefined : json['course_code'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'photo': !exists(json, 'photo') ? undefined : json['photo'],
        'coverPhoto': !exists(json, 'cover_photo') ? undefined : json['cover_photo'],
        '': !exists(json, '') ? undefined : json[''],
    };
}

export function CourseToJSON(value?: Course | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'publisher_id': value.publisherId,
        'source': value.source,
        'course_code': value.courseCode,
        'title': value.title,
        'body': value.body,
        'abstract': value._abstract,
        'status': value.status,
        'categories': value.categories,
        'photo': value.photo,
        'cover_photo': value.coverPhoto,
        '': value.,
    };
}

