/* tslint:disable */
/* eslint-disable */
/**
 * tollgator-core
 * Full api description goes here
 *
 * The version of the OpenAPI document: 1.0
 * Contact: joshuanwafor01@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    businessName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    settlementBank?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    percentageCharge?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    primaryContactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    primaryContactName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    primaryContactPhone?: string;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'businessName': !exists(json, 'business_name') ? undefined : json['business_name'],
        'settlementBank': !exists(json, 'settlement_bank') ? undefined : json['settlement_bank'],
        'accountNumber': !exists(json, 'account_number') ? undefined : json['account_number'],
        'percentageCharge': !exists(json, 'percentage_charge') ? undefined : json['percentage_charge'],
        'primaryContactEmail': !exists(json, 'primary_contact_email') ? undefined : json['primary_contact_email'],
        'primaryContactName': !exists(json, 'primary_contact_name') ? undefined : json['primary_contact_name'],
        'primaryContactPhone': !exists(json, 'primary_contact_phone') ? undefined : json['primary_contact_phone'],
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'business_name': value.businessName,
        'settlement_bank': value.settlementBank,
        'account_number': value.accountNumber,
        'percentage_charge': value.percentageCharge,
        'primary_contact_email': value.primaryContactEmail,
        'primary_contact_name': value.primaryContactName,
        'primary_contact_phone': value.primaryContactPhone,
    };
}

