/* tslint:disable */
/* eslint-disable */
/**
 * tollgator-core
 * Full api description goes here
 *
 * The version of the OpenAPI document: 1.0
 * Contact: joshuanwafor01@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    data?: string;
}

export function InlineResponse400FromJSON(json: any): InlineResponse400 {
    return InlineResponse400FromJSONTyped(json, false);
}

export function InlineResponse400FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse400 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function InlineResponse400ToJSON(value?: InlineResponse400 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'status': value.status,
        'data': value.data,
    };
}

