/* tslint:disable */
/* eslint-disable */
/**
 * tollgator-core
 * Full api description goes here
 *
 * The version of the OpenAPI document: 1.0
 * Contact: joshuanwafor01@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceAttachment
 */
export interface ResourceAttachment {
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    fileType?: ResourceAttachmentFileTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    contentUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceAttachment
     */
    ?: string;
}

/**
* @export
* @enum {string}
*/
export enum ResourceAttachmentFileTypeEnum {
    Video = 'video',
    Audio = 'audio',
    Document = 'document'
}

export function ResourceAttachmentFromJSON(json: any): ResourceAttachment {
    return ResourceAttachmentFromJSONTyped(json, false);
}

export function ResourceAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAttachment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'fileType': !exists(json, 'file_type') ? undefined : json['file_type'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'sourceId': !exists(json, 'source_id') ? undefined : json['source_id'],
        'contentUrl': !exists(json, 'content_url') ? undefined : json['content_url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        '': !exists(json, '') ? undefined : json[''],
    };
}

export function ResourceAttachmentToJSON(value?: ResourceAttachment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'file_type': value.fileType,
        'source': value.source,
        'source_id': value.sourceId,
        'content_url': value.contentUrl,
        'name': value.name,
        '': value.,
    };
}

